### ISSUE TITLE
Defining PyBDM block size 

### ISSUE THREAD

**Issue by lmnor** [sztal/pybdm#13]
Hello PyBDM team!

My hope is to use PyBDM to analyze ocean temperatures data (my data has 2 decimals, for example T = 13.52, 14.07,... etc). And since the data contains 10 different symbols (1,2,3,...,9 and 0) I can't use your code for Non-binary sequences (1D) since it supports a maximum of 9 different symbols. My plan is therefore to remove decimal points and convert the decimal data into binary (e.g. 13.52, 14.07 -> 1352, 1407 -> 00110001 00110011 00110101 00110010, 00110001 00110100 00110000 00110111 etc) and use your code for Binary sequences (1D). So to match the binary data representation I would like to use a block size of 8.

To make sure my PyBDM for Binary sequences (1D) works correctly I tested it against the Online Algorithmic Complexity Calculator (https://complexitycalculator.com) using the standard string (010101010101010101010101010101010101) and standard OACC settings (block size=12, overlap=0, alphabet=2). Both OACC and my PyBDM computed the algorithmic complexity to be 28.5757 bits. 

While testing the code I noticed that when converting the sequence 1111111111 (i.e. ten repetitions of ones) into binary (i.e. _s_=00110001001100010011000100110001001100010011000100110001001100010011000100110001), the PyBDM code for Binary sequences (1D) computes the algorithmic complexity of the binary string _s_ to be **68.71 bits**, while the OACC manages to compute the algorithmic complexity of the binary string _s_ to be **25.39 bits** (block size=**8**, overlap=0, alphabet=2). 

Furthermore, if I set the OACC to default setting (block size=**12**, overlap=0, alphabet=2), it computes the algorithmic complexity of the binary string _s_ to be 90.7816 bits, which would wrongly imply that the string is Martin-Löf random since then K(_s_)/length(_s_)>1, for K(_s_)=90.78, length(_s_)=80.

Is there any way to set the block size to 8 in the PyBDM code for Binary sequences (1D) to replicate the efficient OACC result (25.39 bits)?

![PyBDM](https://user-images.githubusercontent.com/57859531/69006134-4db25d00-092b-11ea-806a-612c5c331a54.png)

![Screenshot_2019-11-17 OACC - Online Algorithmic Complexity Calculator](https://user-images.githubusercontent.com/57859531/69006123-23f93600-092b-11ea-9b00-7484009f34eb.png)

**Comment by sztal** [comment]
Hi!

It seems that there may be some bug in your code, since the PyBDM computation I get (pybdm v0.1.0) is congruent with OACC (up to to some rounding errors). However, it is difficult for me to be 100% sure (or to tell where the error may lie) without your pybdm code.

Below is my code that yield correct results.

```python
import numpy as np
from pybdm import BDM

X = np.array([
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1,
    0, 0, 1, 1, 0, 0, 0, 1
])

bdm = BDM(ndim=1, nsymbols=2, shape=(8,))

bdm.bdm(X)
# results:
# 25.392956301699392

# You can also partially check your computations by inspecting
bdm.decompose_and_count(X)
# result:
# Counter({('00110001', 22.07102820681203): 10})
```

**Comment by lmnor** [comment]
Thank you!

I am glad to say there is no error, but it was my mistake.

Reading through the documentation I never found that the line
`bdm = BDM(ndim=1)`
can be defined as 
`bdm = BDM(ndim=1, nsymbols=2, shape=(8,))`.

I now get exactly the same output as you (25.39 bits). Thank you so much for the clarification and for the PyBDM project!

**Comment by sztal** [comment]
Yes, the default is `shape=(12,)` or `shape=(4,4)` when `ndim=2`. I am glad you pointed out that the documentation is not crystal clear on this issue. We will try to fix it in the next release.

Happy using PyBDM!

**Comment by lmnor** [comment]
Sounds good! Otherwise its an amazing project and super user friendly, it runs great and fast.
