### ISSUE TITLE
Large 1D array of np.uint8

### ISSUE THREAD

**Issue by lowlyocean** [sztal/pybdm#17]
Hello, what is the recommendation for a large 1D array of np.uint8 elements as input, which is initialized from a binary file using np.memmap()?

Seems preferred behavior might be to to specify n_symbols as 256 in BDM constructor, and then each element gets mapped down to sequence of 8 bits internally so that the CTM-B2-D12 gets used

```
    # Create a dataset (256 discrete symbols)
    X = np.full((1,), 255, dtype=np.uint8)

    # Initialize BDM object with 256-symbols alphabet
    bdm = BDM(ndim=1, nsymbols=256)

    # Compute BDM
    print(bdm.bdm(X)) # this fails, but I would expect it to transform [255] to [1 1 1 1 1 1 1 1] internally
```

**Comment by sztal** [comment]
Hi, sorry for the late reply.

There is no way to run BDM for alphabets with 256 symbols. As per the documentation, currently we support 1D arrays with 2, 4, 5, 6 and 9 unique symbols and binary 2D arrays.

The list of available datasets can be obtained with `pybdm.utils.list_ctm_datasets()`.

**Comment by lowlyocean** [comment]
Thank you for responding. To clarify, when loading text data (ASCII or UTF-8) into numpy arry, would you suggest each user to come up with their own solution to convert each character to its underlying array of bits, so that CTM dataset for 1D array with 2 symbols can be leveraged?

I think clustering of text data would be common enough use case for this library to justify happening within the library itself. What do you think?

**Comment by sztal** [comment]
I see. Yes, right now probably the best option is to treat a text as a long binary vector mapping each character to a sequence of 8 bits and concatenating such vectorized letters into one long vector.

And for the second remark the answer is no. It is not a very common usecase at all, and it is not the purpose of the library to implement specific data analytic methods.
